### ISSUE TITLE
Greedycraft Modpack Crash

### ISSUE THREAD

**Issue by reddvilzz** [yeelp/Scaling-Feast#102]
**Mod Version**: 1.6.1
**Minecraft Version**: 1.12.2

**Describe the bug**
Crash when installing the mod to [Greedycraft Mod Pack](https://www.curseforge.com/minecraft/modpacks/greedycraft)

[crash-2021-02-21_18.05.54-client.txt](https://github.com/yeelp/Scaling-Feast/files/6017579/crash-2021-02-21_18.05.54-client.txt)

Removing Scaling Feast removes the crash as well.

**Comment by yeelp** [comment]
Interesting... So something Scaling Feast does causes a crash, but Scaling Feast itself is not the cause of the crash. The crash comes from Loot Bags; so Scaling Feast's loot tables it injects are probably somehow responsible... although the crash log doesn't mention Scaling Feast at all, and I don't think I did anything too dubious when injecting loot tables (pretty standard stuff from what I remember). However, I can see if registering the LootTables fixes the issue.

**Comment by reddvilzz** [comment]
Thanks for the quick fix, though I can't try it yet until you release the 1.7 am I right?

**Comment by yeelp** [comment]
Yup. If all goes well, that should be released some time today

**Comment by reddvilzz** [comment]
It still crash for me, updated the latest 1.7.

[Uploading crash-2021-02-23_07.34.08-client.txt…](Here is the new log), I think  it almost the same.

**Comment by yeelp** [comment]
I loaded Scaling Feast successfully with LootBags in testing, so that's intersting.

So there's a third mod causing problems (Or, more likely, LootBags wasn't the problem, but was what crashed first). Probably LootTweaker, but I have little clue why. I can follow the trace through LootTweaker's source at a later date to try to find the problem I guess

**Comment by reddvilzz** [comment]
Do you need the full log? I can provide it, so maybe there's more details in it.

**Comment by yeelp** [comment]
Might be helpful. If you could post it as a pastebin, that would be great, thanks

**Comment by reddvilzz** [comment]
[Here it is](https://pastebin.ubuntu.com/p/h5RVKQ3wnx/)

**Comment by yeelp** [comment]
Check the [recent prerelease](https://github.com/yeelp/Scaling-Feast/releases/tag/v1.7.1.pre), download the jar (not the sources jar) and check if that works. (Obviously replace the 1.7.0 version present in your Minecraft instance with this one). I'm confident it should work, but on the off chance something goes wrong, I want to be sure before I release it on CurseForge.

**Comment by reddvilzz** [comment]
Okay it is fixed, I can boot into the game without crashing and the mod seems to work well. 

A little minor bug with the hunger bar though if Scaling Feast is used with Classic Bar there will be 2 Hunger bar, one with the Classic Bar and one with Scaling Feast Bar. It's a different Bug though not related to this.

**Comment by yeelp** [comment]
Unfortunately, Classic Bars is closed source so I can't tell how it draws its hunger bar. You can try to go to Scaling Feast's compatibility config setting and turn off the compatibility setting and see if that prevents Classic Bars from drawing its hunger bar.

Apparently Classic Bars' hunger bar doesn't recognize changes to max hunger anyway so that's something that mod author would have to fix.

**Comment by reddvilzz** [comment]
Okay, thanks for the explanation. Yes it must be on Classic Bars that makes the compability, for now just removing classic bar's hunger bar is enough. So I can have Scaling Feast Hunger Bar.
