### ISSUE TITLE
Unlocalized string: attribute.name.scalingfeast.maxHunger

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#79]
**Mod Version**: scalingfeast-1.5.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
attribute.name.scalingfeast.maxHunger is unlocalized.
![image](https://user-images.githubusercontent.com/37945304/83933423-edbbc080-a76d-11ea-84b0-5ffef9da9930.png)

**Steps to Reproduce**
1. `/give @p minecraft:diamond_shovel 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.maxHunger",Name:"a",Amount:10,Operation:0,UUIDLeast:131107,UUIDMost:716360,Slot:"mainhand"}]}`

**Expected behavior**
attribute.name.scalingfeast.maxHunger is localized as "Max Hunger".
![image](https://user-images.githubusercontent.com/37945304/83236455-2994cb80-a159-11ea-853c-001bd19f7af4.png)

**Additional context**
The potion effects of Hunger Plus and Hunger Minus correctly say "Max Hunger".
![image](https://user-images.githubusercontent.com/37945304/83933439-1fcd2280-a76e-11ea-906d-84a56f8341cb.png)

Also, modifiers affecting this attribute that are attached to various items seems to have no effect. Is there something wrong with the setup in the following commands (executed in that order), or is it a bug within Scaling Feast?
1. `/sf setMax @p 500`
2. `/effect @p saturation 2 255`
3. `/give @p minecraft:diamond_shovel 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.maxHunger",Name:"a",Amount:10,Operation:2,UUIDLeast:131107,UUIDMost:71636,Slot:"mainhand"}]}`
4. `/give @p minecraft:diamond_shovel 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.maxHunger",Name:"b",Amount:10,Operation:1,UUIDLeast:131107,UUIDMost:716360,Slot:"mainhand"}]}`
5. `/give @p minecraft:diamond_shovel 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.maxHunger",Name:"b",Amount:10,Operation:0,UUIDLeast:131107,UUIDMost:71630,Slot:"mainhand"}]}`

**Comment by yeelp** [comment]
Actually the attribute has the name ```scalingfeast.maxHungerMod```, so if you switch to that, everything will work.

In hindsight, I'm not sure why I named it that. In the moment, it made sense but looking back, it seems unintuitive.

I mainly did this because the max hunger isn't being stored as a attribute but instead as a capability, with a separate capability for modifying it (which I haven't changed for backwards compatibility, I see now that I should've made it an attribute and any version 2.0 will see that change made). Doing a percentage modifier like "+300% max hunger" won't actually see your max hunger go up by 300% but instead you'll see the modifier value changed by 300% so any bonuses to your max hunger via SOL:Carrot Edition integration etc. will be increased by 300%, if that makes sense.

**Comment by yeelp** [comment]
I actually came up with an idea that should be backwards compatible and should allow a more direct alteration of max hunger

To future me: Store an NBTTagByte in each NBTTagCompound in IFoodCapModifier that represents the operation to perform. Follow the same steps taken by Minecraft for attribute values.
