### ISSUE TITLE
1.12.2 Server-side Crash with Metabolism potion effect.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [yeelp/Scaling-Feast#94]
**Mod Version**:  scalingfeast-1.6.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: 

https://www.curseforge.com/minecraft/modpacks/pixelmon-evolved

( I don't have time to test things because I can use random patches to increase hunger. )

**Describe the bug**
When a player uses an iron apple they get locked as a ticking entity. 

**Steps to Reproduce**
When a player uses an iron apple they get locked as a ticking entity. 

**Expected behavior**
No crashes.

**Screenshots**
[latest.log](https://github.com/yeelp/Scaling-Feast/files/5420537/latest.log)

**Additional context**
I tried going back versions as well.

**Comment by James103** [comment]
Did the previous versions you tried result in the same/a similar crash?

**Comment by P3rf3ctXZer0** [comment]
the exact same crash actually.

**Comment by P3rf3ctXZer0** [comment]
So just so you know the shanks worked fine maybe you could make it so potions enchantments items are a separate mod.

**Comment by yeelp** [comment]
Something is patching FoodStats and removing methods from the FoodStats class with their overridden version.

I thought this would be a problem, but AppleCore should provide a workaround. AppleCore provides API methods to replicate the replaced FoodStats methods, and using those should work. Any problems that arise as a result would most likely mean that mod is incompatible with AppleCore, at which point it'd be out of my hands.

I'll release a patch (1.6.1) to CurseForge shortly (may take a while to show up, you can download the same version here on GitHub as soon as it's available though), and you can check and see if it fixes the problem (which I'm guessing it will.) If it doesn't work, you can post the log again (using something like Pastebin ideally) and reopen this issue, and I can narrow down the problem more.

Also I should specify, the problem isn't with Iron Apples, the problem is with the Metabolism potion effect (again).

**Comment by P3rf3ctXZer0** [comment]
This did indeed fix it 👍
