### ISSUE TITLE
Server Crashes When Using Magma Server Jar

### ISSUE THREAD

**Issue by J0shh** [yeelp/Scaling-Feast#99]
**Minecraft Version**: 1.12.2
**Loaded Mods**: Mods in Rotn BPG Edition Modpack

**Describe the bug**
When trying to run the mod with the Magma Server Jar it causes the server to crash.

**Full Error Log**
https://hastebin.com/ebesuwefex.rb

**Comment by James103** [comment]
Do you get the same crash with just Scaling Feast, Applecore, and Better with Mods installed?

**Comment by yeelp** [comment]
Are you sure this is caused because of Magma Server Jar? I'm not familiar with it in the slightest.

Basically it's trying to get capabilities and something along the way doesn't exist, but I can't say what...

**Comment by James103** [comment]
@J0shh Have you tried opening an issue about that on [Magma's issue tracker](https://github.com/magmafoundation/Magma/issues/new/choose)? (click the one that says "Bug report")

**Comment by J0shh** [comment]
Thanks for the quick response, I am rather certain Magma is the reason it's not working as it works fine with forge, but when using Magma the issue occurs. I'll open an issue with Magma in the hopes of getting it sorted.

**Comment by yeelp** [comment]
After looking into this a little more, I know Magma [has had some problems with Better With Mods before](https://github.com/magmafoundation/Magma/issues/83). Not sure if this is related to the problem here, but it might be. As it stands, it doesn't seem there's anything I can do at the moment, at least not with more info on the issue, so I'm closing this.
